const fs = require('fs')
let c = fs.readFileSync('src/components/PriceAlert.jsx', 'utf8')
c = c.replace('[0.1, 0.5, 1, 2, 3, 5]', '[0.5, 1, 2, 3]')
fs.writeFileSync('src/components/PriceAlert.jsx', c)
console.log('✅ 0.1% und 5% entfernt')