const fs = require('fs')
let c = fs.readFileSync('src/components/PoolDashboard.jsx', 'utf8')
c = c.replace('<ByrealDashboard />', '<ByrealDashboard solPrice={pool.solPrice} />')
fs.writeFileSync('src/components/PoolDashboard.jsx', c)
console.log('✅ solPrice übergeben')